### ISSUE TITLE
Add simple mechanism for navigating to next exercise

### ISSUE THREAD

**Issue by frerich** [mightybyte/monad-challenges#1]
After finishing an exercise, it would be nice to be able to move on to the next exercise with a single click to avoid a mental context switch. A plain 'Next ->' link at the bottom of each page might be nice.

**Comment by mightybyte** [comment]
Yes, I agree.  I would like to do this, but I would like to have them automatically generated so I don't have to maintain them.  I would also like to make it so the set pages (for example this one, http://mightybyte.github.io/monad-challenges/pages/set2.html) are automatically generated as well.  Doing this should make it easy to do the next buttons.

**Comment by jumblesale** [comment]
I'd love to tackle this - could you point me towards a good place to start?

**Comment by mightybyte** [comment]
Great!  What needs to happen is that the [site generator](https://github.com/mightybyte/monad-challenges/blob/gh-pages/hakyll/site.hs) needs to be aware of the overall structure of all the exercises.  Then it needs to make some symbols available to the templates.  Right now I'm envisioning adding probably four symbols to the template context: `prevUrl`, `prevText`, `nextUrl`, `nextText`.  You can see an example of how templates can use stuff from the context [here](https://github.com/mightybyte/monad-challenges/blob/gh-pages/hakyll/templates/default.html#L23).  But using that information in the templates is the easy part.  Probably just a simple if statement to check whether there is a previous/next link.  Exercise 1-5 should link to 1-4 and 1-6.  Exercise 1-6 should link to 1-5 and the set2 index page, etc.

The slightly harder part will be to construct those symbols and put them in the context.  You can see an example of how to add things to the context [here](https://github.com/mightybyte/monad-challenges/blob/gh-pages/hakyll/site.hs#L34).  You'll probably have to have something that gets a list of all the pages/ex*.md files, parses their names, creates a total order on them all, and sets up the four symbols in the context.

Once you've done that, I would also like to use this information to make it so the [set index lists](https://github.com/mightybyte/monad-challenges/blob/gh-pages/hakyll/pages/set1.md) at the end of the set*.md files are auto-generated.

Does this make sense?

**Comment by jumblesale** [comment]
thanks for the detailed response, @mightybyte. I'll have a go and see how I get on!

**Comment by mightybyte** [comment]
In order to make things DRY, I think we will have to create a new template.  Right now default.html is being used to serve all pages.  The path of least resistance would be to add the prev/next links in default.html.  But not every page in the site (namely the home page) needs prev/next links.  So we will need another template that all the exercise pages can use that will add the prev/next links.  If you decide to tackle the auto generation of set indexes, that will require one more template for the set pages.  You can see an example of a single page using multiple templates at [Jasper's Hakyll Blog](https://github.com/jaspervdj/jaspervdj/blob/master/src/Main.hs).

**Comment by shreevatsa** [comment]
IMO although having these automatically generated would be great, it would still be better for the reader to have manually added "next" links than nothing at all.

**Comment by shreevatsa** [comment]
Strangely, although the source `.md` itself contains the next/prev links, e.g. https://github.com/mightybyte/monad-challenges/blob/gh-pages/hakyll/pages/ex1-1.md the rendered html pages don't, e.g. http://mightybyte.github.io/monad-challenges/pages/ex1-1.html (from https://github.com/mightybyte/monad-challenges/blob/gh-pages/pages/ex1-1.html)? Looks like it was added in https://github.com/mightybyte/monad-challenges/pull/71 but never made it to the website.

**Comment by mightybyte** [comment]
Good catch!  I just updated the site.  The links are up now.
