### ISSUE TITLE
Inconsistent types in ex 3.2

### ISSUE THREAD

**Issue by lubomir** [mightybyte/monad-challenges#11]
The text talks shows `allCards :: [Int] -> [Char] -> [Card]` and uses it as `allCards cardRanks cardSuits`. In `MCPrelude`, the type of `cardSuits` is `[String]`, though.

**Comment by joelgrus** [comment]
and also the `show` example uses `Char`

```
show (Card 2 'h') == "2h"
```

**Comment by mightybyte** [comment]
I think this was fixed by this pull request.  https://github.com/mightybyte/monad-challenges/pull/20  Can you verify and close if it is fixed now?

**Comment by lubomir** [comment]
Yes, that fixes it.

Thanks for this awesome project!
