### ISSUE TITLE
Can't build monad-challenges

### ISSUE THREAD

**Issue by mr0re1** [mightybyte/monad-challenges#12]
I'm trying to follow _Getting Started_ instructions, but I face a problem with `cabal install`:

``` sh
 MAC monad-challenges    (master=)
$ cabal --version
cabal-install version 1.22.7.0
using version 1.22.6.0 of the Cabal library
 MAC monad-challenges    (master=)
$ cabal install
Resolving dependencies...
Configuring monad-challenges-0.1.0.0...
Building monad-challenges-0.1.0.0...
Preprocessing library monad-challenges-0.1.0.0...
[1 of 1] Compiling MCPrelude        ( src/MCPrelude.hs, dist/build/MCPrelude.o )

src/MCPrelude.hs:99:5: Not in scope: `undefined'
Failed to install monad-challenges-0.1.0.0
cabal: Error: some packages failed to install:
monad-challenges-0.1.0.0 failed during the building phase. The exception was:
ExitFailure 1
```

**Comment by couchand** [comment]
I was seeing the same issue, and worked around it by adding

```
import Prelude (undefined)
```

along with the other imports around line 128 of `src/MCPrelude.hs`.

**Comment by mr0re1** [comment]
Can confirm that it've solved my problem.

**Comment by pranavmaneriker** [comment]
Equivalently, one can add 

```
undefined = error "Prelude.undefined"
```

in the definitions

**Comment by frerich** [comment]
Oddly enough, I didn't need this. Which GHC versions are you guys using? For me, using GHC 7.10.2, it all worked out of the box.

**Comment by mightybyte** [comment]
@mr0re1 What GHC version are you using?

**Comment by pranavmaneriker** [comment]
@frerich @mightybyte I had the same issue, ghc version 7.6.3

**Comment by coventry** [comment]
I am seeing this error, too, with 7.6.3, which is what ubuntu 14.04 installs.  I'd like to fix it by installing the latest version of haskell.  What's the cleanest way to do that?

**Comment by mr0re1** [comment]
@mightybyte, I use ghc version 7.6.3 on Mac.

**Comment by mightybyte** [comment]
This should be fixed now.  I now have travis set up to test the build back to GHC 7.4.  Thanks for the reports everyone!
