### ISSUE TITLE
How should I output results of each exercise?

### ISSUE THREAD

**Issue by manuca** [mightybyte/monad-challenges#14]
Excuse my ignorance but I don't know how to test the solution of the first challenge without importing any module and without using the default prelude. 

Could you clarify how should we test/execute the solutions to the exercises?

Thanks

**Comment by manuca** [comment]
Ok responding to myself, I did a separate file that imports the module and has a `main`. Thanks

**Comment by mightybyte** [comment]
Hi, I recommend loading your code in ghci and testing it that way.  `ghci Set1.hs` should do the trick.  Then you can just type `fiveRands`, hit enter, and ghci will display the value using the Show instance.
