### ISSUE TITLE
More than one way to write permStep in 3.5

### ISSUE THREAD

**Issue by couchand** [mightybyte/monad-challenges#18]
The text for exercise 3.5 reads:

> Now write that function. There is only one possible way to do it. If you can write a function that compiles, then your answer is correct.

This is, unfortunately, not correct.  I believe the expected behavior is the Cartesian product, but it is indeed possible to write this function in several ways, the most confusing of which is the `zip` form.  Perhaps more details here would be useful.

**Comment by mightybyte** [comment]
Oops, I should have listened to the little voice in the back of my mind that was slightly unsure.  :)  I took out that assertion.  Thanks.
