### ISSUE TITLE
Incorrect type signature & wording imprecision in exercise 1.3

### ISSUE THREAD

**Issue by frerich** [mightybyte/monad-challenges#2]
In exercise 1.3, the `Gen a` alias is introduced. The exercise then asks to use that alias to redefine

```
rand :: Seed -> (Integer, Seed)
randLetter :: Seed -> (Char, Seed)
```

as

```
rand :: Gen Integer
rand :: Gen Char
```

That last type signature should probably be

```
randLetter :: Gen Char
```

That aside, it sounds wrong to talk about 'redefining' the functions. Maybe 'redeclaring' or just 'adjusting the type declaration' would be better. The function definitions themselves don't change at all.

**Comment by mightybyte** [comment]
The s/rand/randLetter/ thing was fixed already.  Good point about "redefine".  I tweaked the wording.
