### ISSUE TITLE
Solutions?

### ISSUE THREAD

**Issue by hath995** [mightybyte/monad-challenges#37]
After finishing a set, which you could detect with tests (quickcheck?), it would be cool if we could see the canonical solutions for these problems. 

I would try to submit a pull request but I am newbie haskeller so I am unaware of what would be canonical.

**Comment by hath995** [comment]
Everything from sections 1-3 was pretty doable with a basic grasp of haskell syntax. The beginning of section 4 seems like something else is required.

Generalizing link and genTwo is obviously something like:

``` haskell
mybind :: m a -> (a -> m b) -> m b
mybind (m a) f = f a
```

However, that seems to be throwing a syntax error. `Parse error in pattern: m`

**Comment by mightybyte** [comment]
You can't have (m a) as a parameter to mybind.  When you define the Monad type class in 4-3 you don't actually implement bind.  You only define its type signature.  The implementation happens for each instance.

**Comment by hath995** [comment]
Oh so the deliverable (in effect) for section 4-1 is just to see the similarity and write the signature?

**Comment by mightybyte** [comment]
Yes.  These signatures won't actually work until you have a Monad type class.  But in exercise 1 we're just trying to generalize by adding a type variable.  There's nothing actually quickcheck-able in 4-1.  That's why I gave the answer hex-encoded.

**Comment by hath995** [comment]
Ah, in other chapters the hex-encoded type signatures were what we were supposed to implement, so this seemed like that was the case.

**Comment by mightybyte** [comment]
Good point.  I added a clarification.
