### ISSUE TITLE
RebindableSyntax and ifThenElse

### ISSUE THREAD

**Issue by liuw** [mightybyte/monad-challenges#39]
The template suggests using RebindableSyntax extension. That leads to ghc desugaring `if ... then ... else` expression to refer to `ifThenElse` function. There is however no `ifThenElse` in scope.

This can be worked around with `case ... of` expression but that's probably not ideal.

My GHC version is 7.10.2.

**Comment by mightybyte** [comment]
Try pulling the repo again.  I think I fixed this issue recently.

**Comment by liuw** [comment]
I cloned the repo yesterday. Neither master nor gh-pages branch seems to
contain fix for this. Did I miss anything?

**Comment by mightybyte** [comment]
Hmm, did you do another cabal install with the latest code?  The fix is in there.

https://github.com/mightybyte/monad-challenges/commit/e2e2e9dc348708d53a3f6975945b4fc0e77647ca

It works for me.  What GHC version do you have?

**Comment by liuw** [comment]
I know why. I'm using master branch while that fix is only available in
gh-pages branch, and I didn't look at the latest gh-pages branch when I
discovered the problem.

I shall use gh-pages in the future.

Thanks. This issue can be closed now.
