### ISSUE TITLE
Surprising drop in difficulty between exercise 1.6 and 2.1

### ISSUE THREAD

**Issue by frerich** [mightybyte/monad-challenges#4]
In exercise 1.6, I'm asked to define somewhat tricky functions `genTwo` or `repRandom`. The next section then starts with exercise 2.1 which merely asks to define a `Maybe` type -- which seems very simple -- only to then define a `Show` instance for `Maybe a` which involves a constraint (`Show a => Show (Maybe a)`). The difficulty level seems to be a bumpy ride here.

**Comment by mightybyte** [comment]
Yes, I did not intend these challenges to be smoothly increasing in level of difficulty.  I intended them to cover several different motivating applications for monads.  So I don't consider this a major problem.
