### ISSUE TITLE
OCaml version

### ISSUE THREAD

**Issue by xguerin** [mightybyte/monad-challenges#42]
Great tutorial. I really enjoyed working through it with OCaml. It's really a great way to work through some of the nifty features of its type system.

I am going through the steps to convert the tutorial for the language. I'll send you a pull request once I'm done in case you are interested into supporting both.

**Comment by mightybyte** [comment]
Cool, sounds great!

**Comment by xguerin** [comment]
What license do you use ? The one in your repo covers source and binary codes, but there is nothing about the content of the challenges.

**Comment by mightybyte** [comment]
Hmmm, good question.  I haven't thought much about it.  I guess I'm not very familiar with what licenses are commonly used for this kind of content.

**Comment by xguerin** [comment]
You can find a whole bunch of them [here](http://www.gnu.org/licenses/license-list.en.html#FreeDocumentationLicenses). I am asking because I've been pondering about the best way to publish the OCaml version of your work. I believe the differences are sufficient to warrant a separate page, and I want to properly attribute the work to whom it is due.

**Comment by mightybyte** [comment]
Thanks for the link.  For now I'm going to go with a Creative Commons Attribution-NonCommercial-ShareAlike 4.0 International License.  I updated the site to clarify that.

**Comment by xguerin** [comment]
Awesome, thanks. Here is the OCaml version: http://xguerin.github.io/ocaml-monad-challenges/. I added a disclaimer at the top of the homepage pointing to your original version and the license. Please let me know if that looks OK to you.

**Comment by mightybyte** [comment]
Looks great!  Glad to see this is inspiring more work in this area.  :)
