### ISSUE TITLE
Improve task description in Set2, Tailprod chapter

### ISSUE THREAD

**Issue by dimsuz** [mightybyte/monad-challenges#48]
I am going through your excellent challanges and this sentence got me a bit confused ([Set2, TailProd](http://mightybyte.github.io/monad-challenges/pages/ex2-6.html)):

> If you want to make these functions work like you want [tailMin, tailMax], you’ll need another helper function. 

It wasn't immediately clear for me what "work like you want" means - I wasn't sure at the moment how I'd like them to work. So I started doing something pointless, but then given up and decoded a hint after which I understood that by "work like you want" author probably meant get rid of extra layer of `Maybe` in `Maybe (Maybe a)`. For some reason I thought it was ok to have it in this a bit ugly way :)

So I suggest to reformulate this somehow, but I am not sure if you'll want a direct hint a-la "strip extra maybe" or if you want the reader to think it through a bit. Maybe something like "if you want to make their types look a bit nicer".

Or maybe it's just me being dumb and this is not an issue at all.

P.S. I could do a PR, but first need to clarify.

**Comment by mightybyte** [comment]
Yeah, this is tricky.  Ideally I would like to not explicitly mention the Maybe Maybe thing.  I just pushed this commit as an attempt to improve the explanation.

https://github.com/mightybyte/monad-challenges/commit/c61e1637e3bd4b8d263bbf8bf13eb7412e8db65a

What do you think?

**Comment by dimsuz** [comment]
I think it's better now, clear. Perhaps even too clear, and 'collapse two levels' is rather explicit. It gives away some details of what's there. If one reads whole thing before experimenting, he might get a hint from this. But it maybe ok. And not sure if many read all chapter before trying. Myself, I am reading only until I encounter some task to do, then return to continue reading.

**Comment by mightybyte** [comment]
I think it's ok.  The text "collapse two levels" doesn't tell them what's being collapsed, so I don't think it gives too much away.
