### ISSUE TITLE
How do you print results of challenges?

### ISSUE THREAD

**Issue by ismail-s** [mightybyte/monad-challenges#49]
There will probs be an obvious solution to this that I haven't thought of, but...

I have installed monad-challenges and have created a file with the following contents:

``` haskell
{-# LANGUAGE MonadComprehensions #-}
{-# LANGUAGE RebindableSyntax  #-}

module Set1 where

import MCPrelude

main = do putStrLn "testing"

```

with the intention being that as I solve the problems, I print out the results on-screen (this is how I have approached the crypto challenges). But this doesn't compile. I get the following error:

```
[1 of 1] Compiling Set1             ( Main.hs, Main.o )

Main.hs:9:11: Not in scope: ‘return’
```

I would just import `return`, but https://mightybyte.github.io/monad-challenges/ says not to import other modules. So, what should I do, or what have other people done?

**Comment by jumblesale** [comment]
I don't know if this is the preferred way of doing it but I've been creating a new file in `src` for each exercise and then running it through `ghci`. so for the first exercise I've created `src/1-1.hs` then I can run it like: `ghci src/1-1.hs`.

the problem with this is that you need to restart ghci any time you make a change. does anyone have a neater solution to this?

**Comment by ismail-s** [comment]
@jumblesale in ghci, the command `:r` reloads the files you have imported.

**Comment by jumblesale** [comment]
great! so then you can just reference whatever you've declared in the file and see the output like that.

**Comment by mightybyte** [comment]
I just pushed a commit adding a short explanation of how to use ghci to the home page.

https://github.com/mightybyte/monad-challenges/commit/91f781f2312e20f0dd7057493700bab66dff61b5
