### ISSUE TITLE
`maximumMay` and `minimumMay` in exercise 2.2 too easy?

### ISSUE THREAD

**Issue by frerich** [mightybyte/monad-challenges#5]
The definitions for `maximumMay` and `minimumMay` which are demaned in exercise 2.2 are apparently supposed to be tricky. The exercise notes

> The maximumMay and minimumMay functions are slightly annoying. Our restricted prelude may prevent you from using things that you would like to use to make your life easier here. This is intentional foreshadowing of things to come. Just bite the bullet and write the function. It’s only 7 short lines including the type signature.

Furthermore, in exercise 2.3, there's a sentence which reads

> If you thought maximumMay from the previous exercise was annoying, then you’ll think this is REALLY annoying.

However, both definitions are quite straightforward. I defined

```
maximumMay :: Ord a => [a] -> Maybe a
maximumMay [] = Nothing
maximumMay xs = Just (foldr1 max xs)

minimumMay :: Ord a => [a] -> Maybe a
minimumMay [] = Nothing
minimumMay xs = Just (foldr1 min xs)
```

It was surprising to see that `head` and `tail` are not available, but `foldr` and `foldr1` are readily available. Maybe the folds should be hidden, too - to force feeling the pain? :-)

**Comment by mightybyte** [comment]
Thanks.  I cleaned this up.  I don't think removing the folds contributes to the point we're trying to make, so I left them in.
