### ISSUE TITLE
Confusion over wording in 1.3

### ISSUE THREAD

**Issue by jdharms** [mightybyte/monad-challenges#51]
Feel free to completely ignore this if I was just completely off here.

When I read:

> Create a type alias that allows you to redefine these two functions with the following type signatures.

I thought it was instructing me to go ahead and create the type alias _and_ redefine the two functions.  So I redefined randLetter, but then realized that I don't have access to the definition to rand anyway, so how can I redefine it with the new type?

After sleeping on this and very carefully rereading, I realize it doesn't mean to redefine the functions, but just to create that type that would allow for the redefinition.

I humbly recommend the following wording for this sentence:

> Create a type alias that would allow us to redefine these two functions with the following type signatures.

With this wording I think it's clear that the student/participant is not actually supposed to redefine the functions at this point.

This is an extremely minor thing, I understand, but I do think it clears up what is being asked in this sentence.

**Comment by mightybyte** [comment]
Done, thanks for the suggestion!
