### ISSUE TITLE
Rephrase exercises statements from Set 2 Ex 2

### ISSUE THREAD

**Issue by larsen** [mightybyte/monad-challenges#52]
I think phrasing in [Set 2 Ex 2](monad-challenges/pages/ex2-2.html) might lead the reader to confusion.

In [Set 2 Ex 1](monad-challenges/pages/ex2-1.html) the reader is supposed to come up with his own version of `Maybe`.

Later, in Set 2 Ex 2, the page says _"The former returns the first element of a list **or Nothing** if the list is empty"_.

If I'm not wrong this is the very first occurrence of `Nothing` in the text. The meaning of `Nothing` in this context is pretty obvious to anyone that had been exposed even superficially to Haskell monads, but I think that not making this assumptions is the point of the exercises. Thus, I think this mention of `Nothing` could be confusing.

I didn't open a PR because I'd like to hear your opinion first. Thanks

**Comment by mightybyte** [comment]
Hmm, good point.  I guess I was thinking that the hex encoded hint in 2-1 was sufficient.  It does contain Nothing, and the exercise does actually ask you to check your answer against the hex-encoded one.  So I think it comes across as something you're supposed to do rather than as a hint you're supposed to try to avoid.  What do you think?

**Comment by larsen** [comment]
You're right, and your remark invalidates my point. What happened in my case is that I skipped the check because I knew Maybe definition already, and proceeded to the next exercise. 

Maybe this could be avoided adding in Set 2 Ex 2 something like _"If you don't know what Nothing means, please make sure you actually checked your solution for the previous exercise"_. But again, if one pays more attention everything will be clear. I think this issue could be closed. Thank you
