### ISSUE TITLE
Improve wording in task description of Set3

### ISSUE THREAD

**Issue by dimsuz** [mightybyte/monad-challenges#53]
Exercise in [Combinations of three things](http://mightybyte.github.io/monad-challenges/pages/ex3-4.html) starts with

> Our allCombs function is more general but it still only lets us generate combinations of two things. It is probably not not immediately obvious how to extend your allCombs function **to do that**. First implement an allCombs3 function that generates combinations of 3 things.

To do what? It reads like there was some additional sentence there which got removed (or is missing). Like

> Our allCombs function is more general but it still only lets us generate combinations of two things. [_We would like it to handle any number of inputs._] It is probably not not immediately obvious how to extend your allCombs function **to do that**.

**Comment by mightybyte** [comment]
Thanks, you're right.  I deleted the whole second sentence.
