### ISSUE TITLE
Confusion with type alias in 1.3

### ISSUE THREAD

**Issue by ismail-s** [mightybyte/monad-challenges#54]
This is probably really obvious (well, the exercise says so), but is it possible to create a type alias (I _think_ this is when you do eg `type blah = existingType` but LYAH and wikibooks call this type synonyms) such that we can do:

```
rand :: Gen Integer
randLetter :: Gen Char
```

I can do:

```
rand :: Seed -> Gen Integer
randLetter :: Seed -> Gen Char
```

as that still takes the parameter, but I can't see how to get rid of the `Seed ->` part.

**Comment by mightybyte** [comment]
Good point.  I changed everything to use the term "type synonym".  Doing a type synonym for it is probably easier than you think:

```
type Gen a = Seed -> (Seed, a)
```

**Comment by ismail-s** [comment]
Ahhh. ~~I don't think I have encountered using -> in such a place/way before, which would explain why I was struggling.~~ I forgot that even functions have a type, which I have seen before, just not thought too much about it.

**Comment by mightybyte** [comment]
I think the way to think about it is that the thing on the right of the equal sign in a type synonym can be any type.  `Seed` is a valid type, `(Seed, a)` is a valid type, and `Seed -> (Seed, a)` is also a valid type.
