### ISSUE TITLE
How do you redo set 1 in ex 4-6?

### ISSUE THREAD

**Issue by ismail-s** [mightybyte/monad-challenges#57]
By the time we get to Exercise 4-6, we have changed `Gen` to being a newtype thingy. But this is incompatible with the types of functions like `rand` in MCPrelude. I can deal with this by creating a new function that wraps the MCPrelude `rand` function in the new Gen, ie

``` haskell
rand' :: Gen Integer
rand' = Gen rand
```

Maybe this should be mentioned in that exercise?

**Comment by mightybyte** [comment]
Good idea!  Done.
