### ISSUE TITLE
Issue with ambiguous "show" reference

### ISSUE THREAD

**Issue by stevenbenjamin** [mightybyte/monad-challenges#58]
Running into this error implementing "show" in set 2:

```
data Maybe a = Nothing | Just a

instance Show a => Show (Maybe a) where
show Nothing =  "Nothing"
show (Just a) = "Just" ++ (show a)
```

> Set2.hs:19:31:
>     Ambiguous occurrence ‘show’
>     It could refer to either ‘Set2.show’, defined at Set2.hs:13:1
>                           or ‘MCPrelude.show’,
>                              imported from ‘MCPrelude’ at Set2.hs:8:1-16
>                              (and originally defined in ‘GHC.Show’)

Is caused by a conflict with the standard prelude? :m -Prelude doesn't fix the issue.

**Comment by Yorwba** [comment]
The problem is that you did not indent your code below the instance declaration correctly, so it looks to the compiler as if you want to  define a new function `Set2.show`, causing ambiguity.

Maybe you should follow this advice from the exercise:

> On the other hand, if writing this instance was too difficult, it might be good to go study some more introductory Haskell materials before continuing here.

**Comment by stevenbenjamin** [comment]
Thanks for the help. It is appreciated. The additional advice, however, was probably unnecessary.
