### ISSUE TITLE
transMaybe?

### ISSUE THREAD

**Issue by gfixler** [mightybyte/monad-challenges#59]
In [section 2-6](http://mightybyte.github.io/monad-challenges/pages/ex2-6.html), the following line appears:

"Now that you have that finished, use transMaybe again to write two more functions tailMax and tailMin. "

`transMaybe` appears only in the hex-encoded type signature, which confused me for a bit, as I looked around for it. It would be nice to mention it before the hex bit, e.g. "Write a function called transMaybe that..."

**Comment by mightybyte** [comment]
It was mentioned in the hint right above.  I updated the text to also mention it outside the hint.  Thanks!
