### ISSUE TITLE
Better descriptions at the beginning of 2.6

### ISSUE THREAD

**Issue by frankitox** [mightybyte/monad-challenges#60]
Hello! First of all, thanks for this tutorials, they're a really good help to understand this fucking monads. Here's the issue: first, I thought that `tailProd [a] == Nothing`, but then, after realizing how the `product` function worked, I get that `tailProd [a] == Just 1`, am I right? So basically my proposal is adding a note that `product [] == 1` and, by extension, `tailProd [a] == Just 1`. Oh, also specify (maybe in the index) if you can use the functions from the previous exercises (I assume you can).

Saludos! from Argentina.

**Comment by mightybyte** [comment]
Thank you for the suggestions, I pushed a commit clarifying things you pointed out.

BTW, I first published these monad challenges when I was on vacation in Argentina!
