### ISSUE TITLE
Explicitly disallow list comprehensions in 3.1

### ISSUE THREAD

**Issue by arknave** [mightybyte/monad-challenges#61]
http://mightybyte.github.io/monad-challenges/pages/ex3-1.html

I thought I'd be able to get away with `allPairs xs ys = [(x, y) | x <- xs, y <- ys]`, but amusingly this doesn't work because of the MCPrelude. I didn't know how list comprehensions were transformed by GHC, it'd be a good thing to note.

**Comment by mightybyte** [comment]
Cool, thanks for the suggestion!
