### ISSUE TITLE
Strange reference to 'challenge #9' and surprising number of expected 'case' expressions in exercise 2.4

### ISSUE THREAD

**Issue by frerich** [mightybyte/monad-challenges#7]
In exercise 2.4, it says:

> If you solved challenge #9 correctly, your function has no fewer than five case statements.

What is 'challenge #9'? And why would I need _five_ case "statements"? My definition of `queryGreek` is

```
queryGreek :: GreekData -> String -> Maybe Double
queryGreek d s = case lookupMay s d of
      Nothing -> Nothing
      Just xs -> case tailMay xs of
              Nothing -> Nothing
              Just t  -> case maximumMay t of
                      Nothing -> Nothing
                      Just m  -> case headMay xs of
                              Nothing -> Nothing
                              Just h  -> divMay (fromIntegral m) (fromIntegral h)
```

Did I miss something? It seems there are only four `case` expressions. That reminds me - I think the text should never talk about 'statements' but always only about 'expressions'.

**Comment by mightybyte** [comment]
I must have miscounted.  I changed it.  Also, s/statement/expression/ is also taken care of.  Thanks.
