### ISSUE TITLE
ex2-5 Feedback

### ISSUE THREAD

**Issue by lukeknxt** [mightybyte/monad-challenges#75]
In ex2-5, we're asked to generalise the pattern in `addSalaries` into a function `ylink`. I experienced confused around two things here:
- Why `ylink` was actually needed when we'd just created `link`. And it wasn't clear whether the original addSalaries should have been implemented with/without link. It was clear after seeing the expected type signature, but may have been helpful to see why link was inadequate to understand what generalisation was expected.
- What y-shaped meant in this context.

**Comment by mightybyte** [comment]
None of these functions are technically *needed*.  They're all just convenience to make certain operations easier to write.

Don't read too much into the names.  They're supposed to be different.  There's a vague reason behind them, but not one that you should pay attention to.  The point is the type signatures and the patterns, not the names.

**Comment by lukeknxt** [comment]
Wasn't necessarily referring to the names. Rather it was hard to see why the generalisation of `ylink` was expected after just having generalised a pattern into `link`. Most of the time the necessity of these generalisations is briefly explained or hinted at, except it didn't feel like it was this time.

**Comment by mightybyte** [comment]
Yeah, it's tough to know the right amount of hints to give.  Part of the premise of this project is to give people fewer hints and promote more digging and exploration.  But if the path is to unclear, that's not useful either.  Did you encounter a particular realization that helped you with this?  Something that we could make into a hint perhaps?
