### ISSUE TITLE
Minor error in install instructions

### ISSUE THREAD

**Issue by mars0i** [mightybyte/monad-challenges#80]
On the main monad-challenges page, it appears that this:
```
cd modad-challenges
```
should be replaced by this:
```
cd monad-challenges/monad-challenges-code
```
(I thought I could add a quick PR instead of an issue, but I'm not familiar with Hakyll, and the link to the Hakyll source on the main github page is currently broken.  Wasn't sure where to look for it.)

**Comment by mightybyte** [comment]
Fixed, thanks!

**Comment by mars0i** [comment]
Great--thanks.  I like to learn by reading, but I've come to feel that you're right about monads.  I recall that years ago I never got recursion until I worked through *The Little Schemer*.
